<?php
namespace Gofann\Content\Entities;

use  Gofann\Content\Entities\EntityAbstract;

class PostEntity extends EntityAbstract{
    public function add( array $data ): ?int {
       return null; // TODO: Implement add() method.
    }

    public function delete( int $id ): ?int {
        return null;// TODO: Implement delete() method.
    }

    public function update( int $id, array $data ): ?int {
        return null;// TODO: Implement update() method.
    }

    public function findOne( int $id ): ?array {
        // TODO: Implement findOne() method.
    }

    public function findMany( array $parameters ): ?array {
        // TODO: Implement findMany() method.
    }

    public function doManyAction( string $action_name, array $action_parameters ): array {
        return parent::doManyAction( $action_name, $action_parameters ); // TODO: Change the autogenerated stub
    }
}